apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsstodiscord
  namespace: discord-bots
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsstodiscord
  template:
    metadata:
      labels:
        app: rsstodiscord
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: rsstodiscord
          image: ghcr.io/lucasvbeek/rss2discord:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: rsstodiscord-config
              mountPath: "/etc/rss2discord"
          env:
            - name: RSS2DISCORD_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rsstodiscord-database
                  key: RSS2DISCORD_DATABASE
      volumes:
        - name: rsstodiscord-config
          configMap:
            name: rsstodiscord-config
